config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Hoptoad Notifier Routes
  match '/notifier_api/v2/notices' => 'notices#create', via: [:get, :post]
  get '/locate/:id' => 'notices#locate', :as => :locate

  resources :notices, only: [:show]
  resources :users do
    member do
      delete :unlink_github
      delete :unlink_google
    end
  end

  resources :site_config, only: [:index] do
    collection do
      put :update
    end
  end

  resources :problems, only: [:index] do
    collection do
      post :destroy_several
      post :resolve_several
      post :unresolve_several
      post :merge_several
      post :unmerge_several
      get :search
    end
  end

  resources :apps do
    resources :problems do
      resources :notices
      resources :comments, only: [:create, :destroy]

      collection do
        post :destroy_all
      end

      member do
        put :resolve
        put :unresolve
        post :create_issue
        post :close_issue
        delete :unlink_issue
      end
    end
    resources :watchers, only: [:destroy, :update]
    member do
      post :regenerate_api_key
    end
  end

  namespace :api do
    namespace :v1 do
      resources :problems, only: [:index, :show], defaults: { format: 'json' }
      resources :notices,  only: [:index], defaults: { format: 'json' }
      resources :stats, only: [], defaults: { format: 'json' } do
        collection do
          get :app
        end
      end
    end
  end

  match '/api/v3/projects/:project_id/create-notice' => 'api/v3/notices#create', via: [:post]
  match '/api/v3/projects/:project_id/notices' => 'api/v3/notices#create', via: [:post, :options]

  root to: 'apps#index'
end

app/views/shared/_flash_messages.html.haml
- unless flash.keys.empty?
  %ul#flash-messages
    - flash.each do |type, message|
      %li{:class => type}= message

app/views/shared/_link_github_account.html.haml
- if Errbit::Config.github_authentication && user == current_user
  - if user.github_account?
    %span.github= link_to "Unlink #{Errbit::Config.github_site_title} account", unlink_github_user_path(user), :method => :delete, :data => { :confirm => "Are you sure?" }
  - else
    %span.github= link_to "Link #{Errbit::Config.github_site_title} account", user_omniauth_authorize_path(:github)

app/views/shared/_link_google_account.html.haml
- if Errbit::Config.google_authentication && user == current_user
  - if user.google_account?
    %span.google= link_to "Unlink #{Errbit::Config.google_site_title} account", unlink_google_user_path, method: :delete, data: { confirm: 'Are you sure?' }
  - else
    %span.google= link_to "Link #{Errbit::Config.google_site_title} account", user_omniauth_authorize_path(:google_oauth2)

app/views/shared/_navigation.html.haml
#nav-bar
  %ul
    %li{:class => active_if_here(:apps)}
      = link_to apps_path do
        %i.fa.fa-briefcase
        = t('.apps')
    %li{:class => active_if_here(:problems)}
      = link_to problems_path do
        %i.fa.fa-warning
        = t('.errors')
    - if user_signed_in? && current_user.admin?
      %li{:class => active_if_here(:users)}
        = link_to users_path do
          %i.fa.fa-users
          = t('.users')
      %li{:class => active_if_here(:site_config)}
        = link_to site_config_index_path do
          %i.fa.fa-wrench
          = t('.config')
  %div.clear

app/views/shared/_session.html.haml
- if current_user
  %ul#session-links
    %li
      = link_to destroy_session_path(:user), :id => 'sign-out', :method => :delete do
        %i.fa.fa-circle
        = t('.sign_out')

    %li= link_to t('.edit_profile'), edit_user_path(current_user), :id => 'edit-profile'