config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  # Hoptoad Notifier Routes
  match '/notifier_api/v2/notices' => 'notices#create', via: [:get, :post]
  get '/locate/:id' => 'notices#locate', :as => :locate

  resources :notices, only: [:show]
  resources :users do
    member do
      delete :unlink_github
      delete :unlink_google
    end
  end

  resources :site_config, only: [:index] do
    collection do
      put :update
    end
  end

  resources :problems, only: [:index] do
    collection do
      post :destroy_several
      post :resolve_several
      post :unresolve_several
      post :merge_several
      post :unmerge_several
      get :search
    end
  end

  resources :apps do
    resources :problems do
      resources :notices
      resources :comments, only: [:create, :destroy]

      collection do
        post :destroy_all
      end

      member do
        put :resolve
        put :unresolve
        post :create_issue
        post :close_issue
        delete :unlink_issue
      end
    end
    resources :watchers, only: [:destroy, :update]
    member do
      post :regenerate_api_key
    end
  end

  namespace :api do
    namespace :v1 do
      resources :problems, only: [:index, :show], defaults: { format: 'json' }
      resources :notices,  only: [:index], defaults: { format: 'json' }
      resources :stats, only: [], defaults: { format: 'json' } do
        collection do
          get :app
        end
      end
    end
  end

  match '/api/v3/projects/:project_id/create-notice' => 'api/v3/notices#create', via: [:post]
  match '/api/v3/projects/:project_id/notices' => 'api/v3/notices#create', via: [:post, :options]

  root to: 'apps#index'
end

app/views/apps/_configuration_instructions.html.haml
%pre
  %code
    :preserve
      # Require the airbrake gem in your App.
      # ---------------------------------------------
      #
      # Ruby - In your Gemfile
      # gem 'airbrake', '~> 5.0'
      #
      # Then add the following to config/initializers/errbit.rb
      # -------------------------------------------------------

      Airbrake.configure do |config|
        config.host = '#{request.base_url}'
        config.project_id = true
        config.project_key = '#{app.api_key}'
      end

app/views/apps/_fields.html.haml
= errors_for app

%div.required
  = f.label :name
  = f.text_field :name

- unless app.new_record?
  %div
    %label Api Key
    %span= app.api_key
    = link_to t('.regenerate_api_key'), regenerate_api_key_app_path(app), :class => 'button', :method => 'post'
%div
  = f.label :repository_branch
  = f.text_field :repository_branch, :placeholder => "master"
%div
  = f.label :github_repo
  = f.text_field :github_repo, :placeholder => "errbit/errbit from https://github.com/errbit/errbit"
%div
  = f.label :bitbucket_repo
  = f.text_field :bitbucket_repo, :placeholder => "errbit/errbit from https://bitbucket.org/errbit/errbit"
%div
  = f.label :asset_host
  %em Used to generate links for JavaScript errors
  = f.text_field :asset_host, :placeholder => "e.g. https://assets.example.com"
%div
  = f.label :current_app_version, 'Latest App Version'
  %em Mobile apps can set this to ignore any error below this version. ie: 1.4.3
  = f.text_field :current_app_version, :placeholder => "e.g. 2.0.1 from the Bundle Identifier on an iOS app"
%fieldset
  %legend Notifications
  %div.checkbox
    = f.check_box :notify_on_errs, 'data-show-when-checked' => '.email_at_notices_nested'
    = f.label :notify_on_errs, 'Notify on errors'
  - if Errbit::Config.per_app_email_at_notices
    %div.email_at_notices_nested{:style => app_decorate.notify_err_display}
      .field-helpertext Send a notification every
      = f.text_field :email_at_notices, :value => app_decorate.email_at_notices
      .field-helpertext times an error occurs (comma separated).

%div.checkbox
  = f.check_box :notify_all_users
  = f.label :notify_all_users, 'Send notifications to all users'

= render "issue_tracker_fields", :f => f
= render "service_notification_fields", :f => f

app/views/apps/_issue_tracker_fields.html.haml
%fieldset
  %legend= t('.legend')
  = f.fields_for :issue_tracker do |issue_tracker_form|
    %div.issue_tracker.nested
      %div.choose
        - issue_tracker_types.each do |tracker_type|
          = issue_tracker_form.label :type_tracker, :class => "label_radio #{tracker_type.label}", :value => tracker_type.label do
            - icon = tracker_type == issue_tracker_form.object.type ? :create : :inactive
            %img.icon{"src" => tracker_type.icons[icon], "data-icon" => tracker_type.icons}
            = issue_tracker_form.radio_button :type_tracker, tracker_type.label, 'data-section' => tracker_type.label
            = tracker_type.label

      - issue_tracker_types.each do |tracker_type|
        %div.tracker_params{:class => tracker_type.params_class(issue_tracker_form.object)}
          = issue_tracker_form.fields_for(:options) do |options_form|
            %p= tracker_type.note
            - tracker_type.fields do |field|
              = options_form.label field.key, field.label
              = field.input(options_form, issue_tracker_form.object)

app/views/apps/_service_notification_fields.html.haml
%fieldset
  %legend Notification Service
  = f.fields_for :notification_service do |w|
    %div.notification_service.nested
      %div.choose
        = label_tag :type_none, :for => label_for_attr(w, 'type_notificationservice'), :class => "label_radio none" do
          = w.radio_button :type, "NotificationService", 'data-section' => 'none'
          (None)
        - NotificationService.subclasses.each do |notification_service|
          = label_tag "type_#{notification_service.label}:", :for => label_for_attr(w, "type_#{notification_service.name.downcase.gsub(':','')}"), :class => "label_radio #{notification_service.label}" do
            = w.radio_button :type, notification_service.name, 'data-section' => notification_service.label
            = notification_service.name[/::(.*)Service/,1].titleize

      %div.notification_params.none{:class => (w.object && !(w.object.class < NotificationService)) ? 'chosen' : nil}
      - NotificationService.subclasses.each do |notification_service|
        %div.notification_params{:class => (w.object.is_a?(notification_service) ? 'chosen ' : '') << notification_service.label}
          - notification_service::FIELDS.each do |field, field_info|
            = w.label field, field_info[:label] || field.to_s.titleize
            - field_type = field == :password ? :password_field : :text_field
            - value = field == :notify_at_notices ? w.object.notify_at_notices.join(", ") : w.object.send(field)
            = w.send field_type, field, :placeholder => field_info[:placeholder], :value => value

      .image_preloader
        - (NotificationService.subclasses.map{|t| t.label } << 'none').each do |notification_service|
          = image_tag "#{notification_service}_inactive.png"
          = image_tag "#{notification_service}_create.png"

app/views/apps/edit.html.haml
- content_for :title, t('.title')
- content_for :action_bar do
  = link_to_copy_attributes_from_other_app
  = link_to 'delete all errs', destroy_all_app_problems_path(app), :method => :post,
    :data => { :confirm => t('apps.confirm_destroy_all_problems') }, :class => 'button'
  = link_to 'delete application', app_path(app), :method => :delete,
    :data => { :confirm => t('apps.confirm_delete') }, :class => 'button'
  = link_to(t('.cancel'), app_path(app), :class => 'button')

= form_for app_decorate do |f|

  = render 'fields', :f => f

  %div.buttons= f.submit t('.update')

app/views/apps/index.html.haml
- content_for :title, t('.title')
- content_for :action_bar do
  - if current_user.admin?
    %span
      = link_to(new_app_path) do
        %i.fa.fa-plus-circle
        = t('.new_app')

%table.apps
  %thead
    %tr
      %th= t('.name')
      - if any_github_repos? || any_bitbucket_repos?
        %th= t('.repository')
      - if any_notification_services?
        %th= t('.notify')
      - if any_issue_trackers?
        %th= t('.tracker')
      %th=t('.errors')
  %tbody
    - apps.each do |app|
      %tr
        %td.name= link_to app.name, app_path(app)
        - if any_github_repos? or any_bitbucket_repos?
          %td.github_repo
            - if app.github_repo?
              = link_to(app.github_repo, app.github_url, :target => '_blank')
            - if app.bitbucket_repo?
              = link_to(app.bitbucket_repo, app.bitbucket_url, :target => '_blank')
        - if any_notification_services?
          %td.notification_service
            - if app.notification_service_configured?
              - notification_service_img = image_tag("#{app.notification_service.label}_goto.png")
              - if app.notification_service.url
                = link_to( notification_service_img, app.notification_service.url, :target => "_blank" )
              - else
                = notification_service_img
        - if any_issue_trackers?
          %td.issue_tracker
            - if app.issue_tracker_configured?
              - tracker_img = image_tag(app.issue_tracker.type.icons[:goto])
              - if app.issue_tracker.url
                = link_to( tracker_img, app.issue_tracker.url )
              - else
                = tracker_img
        %td.count
          - if app.problem_count > 0
            - unresolved = app.unresolved_count
            = link_to unresolved, app_path(app), :class => (unresolved == 0 ? "resolved" : nil)
    - if apps.none?
      %tr
        %td{:colspan => 3}
          %em
            = t('.no_apps')
            = link_to t('.click_to_create'), new_app_path

app/views/apps/new.html.haml
- content_for :title, t('.title')
- content_for :action_bar do
  = link_to_copy_attributes_from_other_app
  = link_to(t('.cancel'), apps_path, :class => 'button')

= form_for app_decorate do |f|

  = render 'fields', :f => f

  %div.buttons= f.submit t('.add_app')

app/views/apps/show.html.haml
- content_for :title, app.name
- content_for :head do
  = auto_discovery_link_tag :atom, app_path(app, User.token_authentication_key => current_user.authentication_token, :format => "atom"), :title => t('.atom_title', :name => app.name, :host => request.host)
- content_for :meta do
  - if app.current_app_version.present?
    %strong="Latest App Version:"
    = app.current_app_version
  %strong=t('.errors_caught')
  = app.problems.count
  %strong=t('.api_key')
  = app.api_key
- content_for :action_bar do
  - if current_user.admin?
    = link_to t('.edit'), edit_app_path(app), :class => 'button'
  - if all_errs
    = link_to t('.unresolved_errs'), app_path(app), :class => 'button'
  - else
    = link_to t('.all_errs'), app_path(app, :all_errs => true), :class => 'button'

  - if app.watched_by?(current_user)
    = link_to t('.unwatch'), app_watcher_path(app_id: app, id: current_user.id), method: :delete, class: 'button'
  - else
    = link_to t('.watch'), app_watcher_path(app_id: app, id: current_user.id), method: :put, class: 'button'

%h3#watchers_toggle
  =t('.watchers')
  %span.click_span=t('.show_hide')
#watchers_div
  - if app.notify_all_users
    %table.watchers
      %thead
        %tr
          %th=t('.all_users_notified')
  - else
    %table.watchers
      %thead
        %tr
          %th=t('.user_or_email')
      %tbody
        - app.watchers.each do |watcher|
          %tr
            %td= watcher.label
        - if app.watchers.none?
          %tr
            %td
              %em= t('.no_watcher')

- if app.github_repo?
  %h3#repository_toggle
    =t('.repository')
    %span.click_span=t('.show_hide')
  #repository_div
    %table.repository
      %thead
        %tr
          %th=t('.github_repo')
      %tbody
        %tr
          %td= link_to(app.github_repo, app.github_url, :target => '_blank')

- if app.problems.any?
  %h3.clear=t('.errors')
  %section
    = render 'problems/search', :all_errs => all_errs, :app_id => app.id
  %br
  %section
    .problem_table{:id => 'problem_table'}
      = render 'problems/table', :problems => problems
- else
  %h3.clear=t('.no_error_yet')
  = render 'configuration_instructions', :app => app